roulette_TD[0] = TextDrawCreate(233.3666, 128.1221, "Box"); // ionoi
TextDrawLetterSize(roulette_TD[0], 0.0000, 25.7027);
TextDrawTextSize(roulette_TD[0], 407.0000, 0.0000);
TextDrawAlignment(roulette_TD[0], 1);
TextDrawColor(roulette_TD[0], -1);
TextDrawUseBox(roulette_TD[0], 1);
TextDrawBoxColor(roulette_TD[0], 9211135);
TextDrawBackgroundColor(roulette_TD[0], 255);
TextDrawFont(roulette_TD[0], 1);
TextDrawSetProportional(roulette_TD[0], 1);
TextDrawSetShadow(roulette_TD[0], 0);

roulette_TD[1] = TextDrawCreate(292.9000, 188.1999, "Box"); // ionoi
TextDrawLetterSize(roulette_TD[1], 0.0000, 12.3000);
TextDrawTextSize(roulette_TD[1], 347.0000, 0.0000);
TextDrawAlignment(roulette_TD[1], 1);
TextDrawColor(roulette_TD[1], -1);
TextDrawUseBox(roulette_TD[1], 1);
TextDrawBoxColor(roulette_TD[1], 160);
TextDrawBackgroundColor(roulette_TD[1], 255);
TextDrawFont(roulette_TD[1], 1);
TextDrawSetProportional(roulette_TD[1], 1);
TextDrawSetShadow(roulette_TD[1], 0);

roulette_TD[2] = TextDrawCreate(293.0000, 188.0000, "LD_SPAC:white"); // ionoi
TextDrawTextSize(roulette_TD[2], 54.0000, 16.0000);
TextDrawAlignment(roulette_TD[2], 1);
TextDrawColor(roulette_TD[2], 9211135);
TextDrawBackgroundColor(roulette_TD[2], 255);
TextDrawFont(roulette_TD[2], 4);
TextDrawSetProportional(roulette_TD[2], 0);
TextDrawSetShadow(roulette_TD[2], 0);
TextDrawSetSelectable(roulette_TD[2], true);

roulette_TD[3] = TextDrawCreate(293.0000, 205.4000, "LD_SPAC:white"); // ionoi
TextDrawTextSize(roulette_TD[3], 54.0000, 16.0000);
TextDrawAlignment(roulette_TD[3], 1);
TextDrawColor(roulette_TD[3], 9211135);
TextDrawBackgroundColor(roulette_TD[3], 255);
TextDrawFont(roulette_TD[3], 4);
TextDrawSetProportional(roulette_TD[3], 0);
TextDrawSetShadow(roulette_TD[3], 0);
TextDrawSetSelectable(roulette_TD[3], true);

roulette_TD[4] = TextDrawCreate(293.0000, 222.7999, "LD_SPAC:white"); // ionoi
TextDrawTextSize(roulette_TD[4], 54.0000, 16.0000);
TextDrawAlignment(roulette_TD[4], 1);
TextDrawColor(roulette_TD[4], 9211135);
TextDrawBackgroundColor(roulette_TD[4], 255);
TextDrawFont(roulette_TD[4], 4);
TextDrawSetProportional(roulette_TD[4], 0);
TextDrawSetShadow(roulette_TD[4], 0);
TextDrawSetSelectable(roulette_TD[4], true);

roulette_TD[5] = TextDrawCreate(306.0000, 240.0000, "LD_SPAC:white"); // ionoi
TextDrawTextSize(roulette_TD[5], 29.0000, 15.0000);
TextDrawAlignment(roulette_TD[5], 1);
TextDrawColor(roulette_TD[5], 9211135);
TextDrawBackgroundColor(roulette_TD[5], 255);
TextDrawFont(roulette_TD[5], 4);
TextDrawSetProportional(roulette_TD[5], 0);
TextDrawSetShadow(roulette_TD[5], 0);
TextDrawSetSelectable(roulette_TD[5], true);

roulette_TD[6] = TextDrawCreate(335.7018, 240.0000, "LD_SPAC:white"); // ionoi
TextDrawTextSize(roulette_TD[6], 11.0000, 15.0000);
TextDrawAlignment(roulette_TD[6], 1);
TextDrawColor(roulette_TD[6], 9211135);
TextDrawBackgroundColor(roulette_TD[6], 255);
TextDrawFont(roulette_TD[6], 4);
TextDrawSetProportional(roulette_TD[6], 0);
TextDrawSetShadow(roulette_TD[6], 0);
TextDrawSetSelectable(roulette_TD[6], true);

roulette_TD[7] = TextDrawCreate(319.7001, 190.0000, "bronze"); // ionoi
TextDrawLetterSize(roulette_TD[7], 0.3133, 1.3718);
TextDrawAlignment(roulette_TD[7], 2);
TextDrawColor(roulette_TD[7], -1);
TextDrawBackgroundColor(roulette_TD[7], 255);
TextDrawFont(roulette_TD[7], 3);
TextDrawSetProportional(roulette_TD[7], 1);
TextDrawSetShadow(roulette_TD[7], 0);

roulette_TD[8] = TextDrawCreate(319.7001, 207.5010, "silver"); // ionoi
TextDrawLetterSize(roulette_TD[8], 0.3133, 1.3718);
TextDrawAlignment(roulette_TD[8], 2);
TextDrawColor(roulette_TD[8], -1);
TextDrawBackgroundColor(roulette_TD[8], 255);
TextDrawFont(roulette_TD[8], 3);
TextDrawSetProportional(roulette_TD[8], 1);
TextDrawSetShadow(roulette_TD[8], 0);

roulette_TD[9] = TextDrawCreate(319.7001, 224.8021, "gold"); // ionoi
TextDrawLetterSize(roulette_TD[9], 0.3133, 1.3718);
TextDrawAlignment(roulette_TD[9], 2);
TextDrawColor(roulette_TD[9], -1);
TextDrawBackgroundColor(roulette_TD[9], 255);
TextDrawFont(roulette_TD[9], 3);
TextDrawSetProportional(roulette_TD[9], 1);
TextDrawSetShadow(roulette_TD[9], 0);

roulette_TD[10] = TextDrawCreate(320.4002, 241.3031, "roll"); // ionoi
TextDrawLetterSize(roulette_TD[10], 0.3026, 1.2971);
TextDrawAlignment(roulette_TD[10], 2);
TextDrawColor(roulette_TD[10], -1);
TextDrawBackgroundColor(roulette_TD[10], 255);
TextDrawFont(roulette_TD[10], 3);
TextDrawSetProportional(roulette_TD[10], 1);
TextDrawSetShadow(roulette_TD[10], 0);

roulette_TD[11] = TextDrawCreate(341.1014, 241.3031, "0"); // ionoi
TextDrawLetterSize(roulette_TD[11], 0.3026, 1.2971);
TextDrawAlignment(roulette_TD[11], 2);
TextDrawColor(roulette_TD[11], -1);
TextDrawBackgroundColor(roulette_TD[11], 255);
TextDrawFont(roulette_TD[11], 3);
TextDrawSetProportional(roulette_TD[11], 1);
TextDrawSetShadow(roulette_TD[11], 0);

roulette_TD[12] = TextDrawCreate(316.4332, 278.2556, "win"); // ionoi
TextDrawLetterSize(roulette_TD[12], 0.7530, 2.1309);
TextDrawAlignment(roulette_TD[12], 1);
TextDrawColor(roulette_TD[12], -1);
TextDrawBackgroundColor(roulette_TD[12], 255);
TextDrawFont(roulette_TD[12], 0);
TextDrawSetProportional(roulette_TD[12], 1);
TextDrawSetShadow(roulette_TD[12], 0);