GreenZone[playerid][0] = CreatePlayerTextDraw(playerid, 587.057250, 226.916671, "LD_SPAC:white");
PlayerTextDrawLetterSize(playerid, GreenZone[playerid][0], 0.000000, 0.000000);
PlayerTextDrawTextSize(playerid, GreenZone[playerid][0], 54.348464, 11.666670);
PlayerTextDrawAlignment(playerid, GreenZone[playerid][0], 1);
PlayerTextDrawColor(playerid, GreenZone[playerid][0], 808464639);
PlayerTextDrawSetShadow(playerid, GreenZone[playerid][0], 0);
PlayerTextDrawSetOutline(playerid, GreenZone[playerid][0], 0);
PlayerTextDrawFont(playerid, GreenZone[playerid][0], 4);

GreenZone[playerid][1] = CreatePlayerTextDraw(playerid, 616.105590, 228.083267, "GreenZone");
PlayerTextDrawLetterSize(playerid, GreenZone[playerid][1], 0.166544, 0.841666);
PlayerTextDrawAlignment(playerid, GreenZone[playerid][1], 2);
PlayerTextDrawColor(playerid, GreenZone[playerid][1], -1);
PlayerTextDrawSetShadow(playerid, GreenZone[playerid][1], 0);
PlayerTextDrawSetOutline(playerid, GreenZone[playerid][1], 1);
PlayerTextDrawBackgroundColor(playerid, GreenZone[playerid][1], 51);
PlayerTextDrawFont(playerid, GreenZone[playerid][1], 2);
PlayerTextDrawSetProportional(playerid, GreenZone[playerid][1], 1);

GreenZone[playerid][2] = CreatePlayerTextDraw(playerid, 575.812561, 223.416702, "LD_BEAT:chit");
PlayerTextDrawLetterSize(playerid, GreenZone[playerid][2], 0.000000, 0.000000);
PlayerTextDrawTextSize(playerid, GreenZone[playerid][2], 19.677871, 18.083307);
PlayerTextDrawAlignment(playerid, GreenZone[playerid][2], 1);
PlayerTextDrawColor(playerid, GreenZone[playerid][2], 9053183);
PlayerTextDrawSetShadow(playerid, GreenZone[playerid][2], 0);
PlayerTextDrawSetOutline(playerid, GreenZone[playerid][2], 0);
PlayerTextDrawFont(playerid, GreenZone[playerid][2], 4);

GreenZone[playerid][3] = CreatePlayerTextDraw(playerid, 585.651733, 226.333358, "!");
PlayerTextDrawLetterSize(playerid, GreenZone[playerid][3], 0.335680, 1.174166);
PlayerTextDrawAlignment(playerid, GreenZone[playerid][3], 2);
PlayerTextDrawColor(playerid, GreenZone[playerid][3], -1);
PlayerTextDrawUseBox(playerid, GreenZone[playerid][3], true);
PlayerTextDrawBoxColor(playerid, GreenZone[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, GreenZone[playerid][3], 0);
PlayerTextDrawSetOutline(playerid, GreenZone[playerid][3], 1);
PlayerTextDrawBackgroundColor(playerid, GreenZone[playerid][3], 51);
PlayerTextDrawFont(playerid, GreenZone[playerid][3], 1);
PlayerTextDrawSetProportional(playerid, GreenZone[playerid][3], 1);