MaffiaTXT[playerid][0] = CreatePlayerTextDraw(playerid, 4.685212, 237.416671, "LD_SPAC:white");
PlayerTextDrawLetterSize(playerid, MaffiaTXT[playerid][0], 0.000000, 0.000000);
PlayerTextDrawTextSize(playerid, MaffiaTXT[playerid][0], 90.424591, 48.416679);
PlayerTextDrawAlignment(playerid, MaffiaTXT[playerid][0], 1);
PlayerTextDrawColor(playerid, MaffiaTXT[playerid][0], 741092607);
PlayerTextDrawSetShadow(playerid, MaffiaTXT[playerid][0], 0);
PlayerTextDrawSetOutline(playerid, MaffiaTXT[playerid][0], 0);
PlayerTextDrawFont(playerid, MaffiaTXT[playerid][0], 4);

MaffiaTXT[playerid][1] = CreatePlayerTextDraw(playerid, 7.027818, 240.333328, "LD_SPAC:white");
PlayerTextDrawLetterSize(playerid, MaffiaTXT[playerid][1], 0.000000, 0.000000);
PlayerTextDrawTextSize(playerid, MaffiaTXT[playerid][1], 21.083456, 42.583358);
PlayerTextDrawAlignment(playerid, MaffiaTXT[playerid][1], 1);
PlayerTextDrawColor(playerid, MaffiaTXT[playerid][1], 1296911871);
PlayerTextDrawSetShadow(playerid, MaffiaTXT[playerid][1], 0);
PlayerTextDrawSetOutline(playerid, MaffiaTXT[playerid][1], 0);
PlayerTextDrawFont(playerid, MaffiaTXT[playerid][1], 4);

MaffiaTXT[playerid][2] = CreatePlayerTextDraw(playerid, 27.174232, 267.750000, "LD_SPAC:white");
PlayerTextDrawLetterSize(playerid, MaffiaTXT[playerid][2], 0.000000, 0.000000);
PlayerTextDrawTextSize(playerid, MaffiaTXT[playerid][2], 59.502189, 15.166687);
PlayerTextDrawAlignment(playerid, MaffiaTXT[playerid][2], 1);
PlayerTextDrawColor(playerid, MaffiaTXT[playerid][2], 1296911871);
PlayerTextDrawSetShadow(playerid, MaffiaTXT[playerid][2], 0);
PlayerTextDrawSetOutline(playerid, MaffiaTXT[playerid][2], 0);
PlayerTextDrawFont(playerid, MaffiaTXT[playerid][2], 4);

MaffiaTXT[playerid][3] = CreatePlayerTextDraw(playerid, 71.683761, 240.333175, "LD_SPAC:white");
PlayerTextDrawLetterSize(playerid, MaffiaTXT[playerid][3], 0.000000, 0.000000);
PlayerTextDrawTextSize(playerid, MaffiaTXT[playerid][3], 21.083450, 42.583358);
PlayerTextDrawAlignment(playerid, MaffiaTXT[playerid][3], 1);
PlayerTextDrawColor(playerid, MaffiaTXT[playerid][3], 1296911871);
PlayerTextDrawSetShadow(playerid, MaffiaTXT[playerid][3], 0);
PlayerTextDrawSetOutline(playerid, MaffiaTXT[playerid][3], 0);
PlayerTextDrawFont(playerid, MaffiaTXT[playerid][3], 4);

MaffiaTXT[playerid][4] = CreatePlayerTextDraw(playerid, 17.803783, 265.416687, "6");
PlayerTextDrawLetterSize(playerid, MaffiaTXT[playerid][4], 0.262122, 1.553333);
PlayerTextDrawAlignment(playerid, MaffiaTXT[playerid][4], 2);
PlayerTextDrawColor(playerid, MaffiaTXT[playerid][4], -1);
PlayerTextDrawSetShadow(playerid, MaffiaTXT[playerid][4], 0);
PlayerTextDrawSetOutline(playerid, MaffiaTXT[playerid][4], 1);
PlayerTextDrawBackgroundColor(playerid, MaffiaTXT[playerid][4], 51);
PlayerTextDrawFont(playerid, MaffiaTXT[playerid][4], 3);
PlayerTextDrawSetProportional(playerid, MaffiaTXT[playerid][4], 1);

MaffiaTXT[playerid][5] = CreatePlayerTextDraw(playerid, 49.663208, 246.166717, "25 00");
PlayerTextDrawLetterSize(playerid, MaffiaTXT[playerid][5], 0.308975, 1.331667);
PlayerTextDrawAlignment(playerid, MaffiaTXT[playerid][5], 2);
PlayerTextDrawColor(playerid, MaffiaTXT[playerid][5], -1);
PlayerTextDrawSetShadow(playerid, MaffiaTXT[playerid][5], 0);
PlayerTextDrawSetOutline(playerid, MaffiaTXT[playerid][5], 1);
PlayerTextDrawBackgroundColor(playerid, MaffiaTXT[playerid][5], 51);
PlayerTextDrawFont(playerid, MaffiaTXT[playerid][5], 3);
PlayerTextDrawSetProportional(playerid, MaffiaTXT[playerid][5], 1);

MaffiaTXT[playerid][6] = CreatePlayerTextDraw(playerid, 81.991256, 265.416656, "14");
PlayerTextDrawLetterSize(playerid, MaffiaTXT[playerid][6], 0.262122, 1.553333);
PlayerTextDrawAlignment(playerid, MaffiaTXT[playerid][6], 2);
PlayerTextDrawColor(playerid, MaffiaTXT[playerid][6], -1);
PlayerTextDrawSetShadow(playerid, MaffiaTXT[playerid][6], 0);
PlayerTextDrawSetOutline(playerid, MaffiaTXT[playerid][6], 1);
PlayerTextDrawBackgroundColor(playerid, MaffiaTXT[playerid][6], 51);
PlayerTextDrawFont(playerid, MaffiaTXT[playerid][6], 3);
PlayerTextDrawSetProportional(playerid, MaffiaTXT[playerid][6], 1);

MaffiaTXT[playerid][7] = CreatePlayerTextDraw(playerid, 8.901903, 244.416656, "LD_SPAC:white");
PlayerTextDrawLetterSize(playerid, MaffiaTXT[playerid][7], 0.000000, 0.000000);
PlayerTextDrawTextSize(playerid, MaffiaTXT[playerid][7], 17.335287, 18.083312);
PlayerTextDrawAlignment(playerid, MaffiaTXT[playerid][7], 1);
PlayerTextDrawColor(playerid, MaffiaTXT[playerid][7], -1523963137);
PlayerTextDrawSetShadow(playerid, MaffiaTXT[playerid][7], 0);
PlayerTextDrawSetOutline(playerid, MaffiaTXT[playerid][7], 0);
PlayerTextDrawFont(playerid, MaffiaTXT[playerid][7], 4);

MaffiaTXT[playerid][8] = CreatePlayerTextDraw(playerid, 73.557800, 244.416687, "LD_SPAC:white");
PlayerTextDrawLetterSize(playerid, MaffiaTXT[playerid][8], 0.000000, 0.000000);
PlayerTextDrawTextSize(playerid, MaffiaTXT[playerid][8], 17.335281, 18.083328);
PlayerTextDrawAlignment(playerid, MaffiaTXT[playerid][8], 1);
PlayerTextDrawColor(playerid, MaffiaTXT[playerid][8], -2139062017);
PlayerTextDrawSetShadow(playerid, MaffiaTXT[playerid][8], 0);
PlayerTextDrawSetOutline(playerid, MaffiaTXT[playerid][8], 0);
PlayerTextDrawFont(playerid, MaffiaTXT[playerid][8], 4);

MaffiaTXT[playerid][9] = CreatePlayerTextDraw(playerid, 4.685212, 290.500030, "LD_SPAC:white");
PlayerTextDrawLetterSize(playerid, MaffiaTXT[playerid][9], 0.000000, 0.000000);
PlayerTextDrawTextSize(playerid, MaffiaTXT[playerid][9], 89.956069, 15.750038);
PlayerTextDrawAlignment(playerid, MaffiaTXT[playerid][9], 1);
PlayerTextDrawColor(playerid, MaffiaTXT[playerid][9], 741092607);
PlayerTextDrawSetShadow(playerid, MaffiaTXT[playerid][9], 0);
PlayerTextDrawSetOutline(playerid, MaffiaTXT[playerid][9], 0);
PlayerTextDrawFont(playerid, MaffiaTXT[playerid][9], 4);

MaffiaTXT[playerid][10] = CreatePlayerTextDraw(playerid, 50.131782, 291.083312, "Keon_Stromzy");
PlayerTextDrawLetterSize(playerid, MaffiaTXT[playerid][10], 0.166076, 1.314166);
PlayerTextDrawAlignment(playerid, MaffiaTXT[playerid][10], 2);
PlayerTextDrawColor(playerid, MaffiaTXT[playerid][10], -1);
PlayerTextDrawUseBox(playerid, MaffiaTXT[playerid][10], true);
PlayerTextDrawBoxColor(playerid, MaffiaTXT[playerid][10], 0);
PlayerTextDrawSetShadow(playerid, MaffiaTXT[playerid][10], 0);
PlayerTextDrawSetOutline(playerid, MaffiaTXT[playerid][10], 1);
PlayerTextDrawBackgroundColor(playerid, MaffiaTXT[playerid][10], 51);
PlayerTextDrawFont(playerid, MaffiaTXT[playerid][10], 2);
PlayerTextDrawSetProportional(playerid, MaffiaTXT[playerid][10], 1);