roulette_PTD[playerid][0] = CreatePlayerTextDraw(playerid, 234.8000, 129.3666, "LD_SPAC:WHITE"); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][0], 55.0000, 55.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][0], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][0], -1448476417);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][0], 255);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][0], 4);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][0], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][0], 0);

roulette_PTD[playerid][1] = CreatePlayerTextDraw(playerid, 292.5002, 129.3999, "LD_SPAC:WHITE"); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][1], 55.0000, 55.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][1], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][1], -1448476417);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][1], 255);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][1], 4);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][1], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][1], 0);

roulette_PTD[playerid][2] = CreatePlayerTextDraw(playerid, 350.1000, 129.4000, "LD_SPAC:WHITE"); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][2], 55.0000, 55.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][2], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][2], -1448476417);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][2], 255);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][2], 4);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][2], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][2], 0);

roulette_PTD[playerid][3] = CreatePlayerTextDraw(playerid, 350.2000, 186.8998, "LD_SPAC:WHITE"); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][3], 55.0000, 55.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][3], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][3], -1448476417);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][3], 255);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][3], 4);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][3], 0);

roulette_PTD[playerid][4] = CreatePlayerTextDraw(playerid, 350.3000, 244.9000, "LD_SPAC:WHITE"); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][4], 55.0000, 55.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][4], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][4], -1448476417);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][4], 255);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][4], 4);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][4], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][4], 0);

roulette_PTD[playerid][5] = CreatePlayerTextDraw(playerid, 350.2000, 302.4999, "LD_SPAC:WHITE"); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][5], 55.0000, 55.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][5], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][5], -1448476417);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][5], 255);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][5], 4);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][5], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][5], 0);

roulette_PTD[playerid][6] = CreatePlayerTextDraw(playerid, 292.2000, 302.6015, "LD_SPAC:WHITE"); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][6], 55.0000, 55.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][6], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][6], -1448476417);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][6], 255);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][6], 4);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][6], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][6], 0);

roulette_PTD[playerid][7] = CreatePlayerTextDraw(playerid, 234.6999, 302.4999, "LD_SPAC:WHITE"); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][7], 55.0000, 55.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][7], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][7], -1448476417);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][7], 255);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][7], 4);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][7], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][7], 0);

roulette_PTD[playerid][8] = CreatePlayerTextDraw(playerid, 235.0000, 244.6000, "LD_SPAC:WHITE"); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][8], 55.0000, 55.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][8], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][8], -1448476417);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][8], 255);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][8], 4);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][8], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][8], 0);

roulette_PTD[playerid][9] = CreatePlayerTextDraw(playerid, 235.0000, 186.4999, "LD_SPAC:WHITE"); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][9], 55.0000, 55.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][9], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][9], -1448476417);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][9], 255);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][9], 4);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][9], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][9], 0);

roulette_PTD[playerid][10] = CreatePlayerTextDraw(playerid, 236.2998, 131.2998, ""); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][10], 50.0000, 50.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][10], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][10], -1);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][10], 5);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][10], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][10], 0);
PlayerTextDrawSetPreviewModel(playerid, roulette_PTD[playerid][10], 0);
PlayerTextDrawSetPreviewRot(playerid, roulette_PTD[playerid][10], 0.0000, 0.0000, 0.0000, 1.0000);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][10], 0xFFFFFF00);

roulette_PTD[playerid][11] = CreatePlayerTextDraw(playerid, 293.0000, 131.0000, ""); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][11], 50.0000, 50.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][11], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][11], -1);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][11], 5);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][11], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][11], 0);
PlayerTextDrawSetPreviewModel(playerid, roulette_PTD[playerid][11], 0);
PlayerTextDrawSetPreviewRot(playerid, roulette_PTD[playerid][11], 0.0000, 0.0000, 0.0000, 1.0000);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][11], 0xFFFFFF00);

roulette_PTD[playerid][12] = CreatePlayerTextDraw(playerid, 351.0000, 130.0000, ""); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][12], 50.0000, 50.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][12], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][12], -1);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][12], 5);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][12], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][12], 0);
PlayerTextDrawSetPreviewModel(playerid, roulette_PTD[playerid][12], 0);
PlayerTextDrawSetPreviewRot(playerid, roulette_PTD[playerid][12], 0.0000, 0.0000, 0.0000, 1.0000);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][12], 0xFFFFFF00);

roulette_PTD[playerid][13] = CreatePlayerTextDraw(playerid, 351.0000, 188.0000, ""); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][13], 50.0000, 50.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][13], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][13], -1);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][13], 5);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][13], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][13], 0);
PlayerTextDrawSetPreviewModel(playerid, roulette_PTD[playerid][13], 0);
PlayerTextDrawSetPreviewRot(playerid, roulette_PTD[playerid][13], 0.0000, 0.0000, 0.0000, 1.0000);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][13], 0xFFFFFF00);

roulette_PTD[playerid][14] = CreatePlayerTextDraw(playerid, 352.0000, 246.0000, ""); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][14], 50.0000, 50.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][14], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][14], -1);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][14], 5);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][14], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][14], 0);
PlayerTextDrawSetPreviewModel(playerid, roulette_PTD[playerid][14], 0);
PlayerTextDrawSetPreviewRot(playerid, roulette_PTD[playerid][14], 0.0000, 0.0000, 0.0000, 1.0000);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][14], 0xFFFFFF00);

roulette_PTD[playerid][15] = CreatePlayerTextDraw(playerid, 353.0000, 306.0000, ""); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][15], 50.0000, 50.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][15], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][15], -1);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][15], 5);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][15], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][15], 0);
PlayerTextDrawSetPreviewModel(playerid, roulette_PTD[playerid][15], 0);
PlayerTextDrawSetPreviewRot(playerid, roulette_PTD[playerid][15], 0.0000, 0.0000, 0.0000, 1.0000);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][15], 0xFFFFFF00);

roulette_PTD[playerid][16] = CreatePlayerTextDraw(playerid, 292.0000, 305.0000, ""); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][16], 50.0000, 50.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][16], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][16], -1);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][16], 5);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][16], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][16], 0);
PlayerTextDrawSetPreviewModel(playerid, roulette_PTD[playerid][16], 0);
PlayerTextDrawSetPreviewRot(playerid, roulette_PTD[playerid][16], 0.0000, 0.0000, 0.0000, 1.0000);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][16], 0xFFFFFF00);

roulette_PTD[playerid][17] = CreatePlayerTextDraw(playerid, 237.0000, 305.0000, ""); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][17], 50.0000, 50.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][17], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][17], -1);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][17], 5);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][17], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][17], 0);
PlayerTextDrawSetPreviewModel(playerid, roulette_PTD[playerid][17], 0);
PlayerTextDrawSetPreviewRot(playerid, roulette_PTD[playerid][17], 0.0000, 0.0000, 0.0000, 1.0000);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][17], 0xFFFFFF00);

roulette_PTD[playerid][18] = CreatePlayerTextDraw(playerid, 238.0000, 246.0000, ""); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][18], 50.0000, 50.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][18], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][18], -1);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][18], 5);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][18], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][18], 0);
PlayerTextDrawSetPreviewModel(playerid, roulette_PTD[playerid][18], 0);
PlayerTextDrawSetPreviewRot(playerid, roulette_PTD[playerid][18], 0.0000, 0.0000, 0.0000, 1.0000);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][18], 0xFFFFFF00);

roulette_PTD[playerid][19] = CreatePlayerTextDraw(playerid, 236.0000, 189.0000, ""); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][19], 50.0000, 50.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][19], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][19], -1);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][19], 5);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][19], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][19], 0);
PlayerTextDrawSetPreviewModel(playerid, roulette_PTD[playerid][19], 0);
PlayerTextDrawSetPreviewRot(playerid, roulette_PTD[playerid][19], 0.0000, 0.0000, 0.0000, 1.0000);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][19], 0xFFFFFF00);

roulette_PTD[playerid][20] = CreatePlayerTextDraw(playerid, 290.4664, 254.3075, ""); // ionoi
PlayerTextDrawTextSize(playerid, roulette_PTD[playerid][20], 59.0000, 43.0000);
PlayerTextDrawAlignment(playerid, roulette_PTD[playerid][20], 1);
PlayerTextDrawColor(playerid, roulette_PTD[playerid][20], -1);
PlayerTextDrawFont(playerid, roulette_PTD[playerid][20], 5);
PlayerTextDrawSetProportional(playerid, roulette_PTD[playerid][20], 0);
PlayerTextDrawSetShadow(playerid, roulette_PTD[playerid][20], 0);
PlayerTextDrawSetPreviewModel(playerid, roulette_PTD[playerid][20], 120);
PlayerTextDrawSetPreviewRot(playerid, roulette_PTD[playerid][20], 0.0000, 0.0000, 0.0000, 1.0000);
PlayerTextDrawBackgroundColor(playerid, roulette_PTD[playerid][20], 0xFFFFFF00);