speedometr[playerid][0] = CreatePlayerTextDraw(playerid, 636.666503, 367.864532, "usebox");
PlayerTextDrawLetterSize(playerid, speedometr[playerid][0], 0.000000, 5.759377);
PlayerTextDrawTextSize(playerid, speedometr[playerid][0], 490.444458, 0.000000);
PlayerTextDrawAlignment(playerid, speedometr[playerid][0], 1);
PlayerTextDrawColor(playerid, speedometr[playerid][0], 0);
PlayerTextDrawUseBox(playerid, speedometr[playerid][0], true);
PlayerTextDrawBoxColor(playerid, speedometr[playerid][0], 471604424);
PlayerTextDrawSetShadow(playerid, speedometr[playerid][0], 0);
PlayerTextDrawSetOutline(playerid, speedometr[playerid][0], 0);
PlayerTextDrawFont(playerid, speedometr[playerid][0], 0);

speedometr[playerid][1] = CreatePlayerTextDraw(playerid, 636.666687, 367.864624, "usebox");
PlayerTextDrawLetterSize(playerid, speedometr[playerid][1], 0.000000, -0.095430);
PlayerTextDrawTextSize(playerid, speedometr[playerid][1], 490.444458, 0.000000);
PlayerTextDrawAlignment(playerid, speedometr[playerid][1], 1);
PlayerTextDrawColor(playerid, speedometr[playerid][1], 0);
PlayerTextDrawUseBox(playerid, speedometr[playerid][1], true);
PlayerTextDrawBoxColor(playerid, speedometr[playerid][1], -668439399);
PlayerTextDrawSetShadow(playerid, speedometr[playerid][1], 0);
PlayerTextDrawSetOutline(playerid, speedometr[playerid][1], 0);
PlayerTextDrawFont(playerid, speedometr[playerid][1], 0);

speedometr[playerid][2] = CreatePlayerTextDraw(playerid, 495.999877, 375.822235, "hud:radar_girlfriend");
PlayerTextDrawLetterSize(playerid, speedometr[playerid][2], 0.000000, 0.000000);
PlayerTextDrawTextSize(playerid, speedometr[playerid][2], 9.777785, 9.955574);
PlayerTextDrawAlignment(playerid, speedometr[playerid][2], 1);
PlayerTextDrawColor(playerid, speedometr[playerid][2], -1);
PlayerTextDrawSetShadow(playerid, speedometr[playerid][2], 0);
PlayerTextDrawSetOutline(playerid, speedometr[playerid][2], 0);
PlayerTextDrawFont(playerid, speedometr[playerid][2], 4);

speedometr[playerid][3] = CreatePlayerTextDraw(playerid, 495.666595, 389.266540, "hud:radar_impound");
PlayerTextDrawLetterSize(playerid, speedometr[playerid][3], 0.000000, 0.000000);
PlayerTextDrawTextSize(playerid, speedometr[playerid][3], 10.222229, 11.946682);
PlayerTextDrawAlignment(playerid, speedometr[playerid][3], 1);
PlayerTextDrawColor(playerid, speedometr[playerid][3], -1);
PlayerTextDrawSetShadow(playerid, speedometr[playerid][3], 0);
PlayerTextDrawSetOutline(playerid, speedometr[playerid][3], 0);
PlayerTextDrawFont(playerid, speedometr[playerid][3], 4);

speedometr[playerid][4] = CreatePlayerTextDraw(playerid, 495.333160, 407.688781, "hud:radar_centre");
PlayerTextDrawLetterSize(playerid, speedometr[playerid][4], 0.000000, 0.000000);
PlayerTextDrawTextSize(playerid, speedometr[playerid][4], 10.666670, 10.951128);
PlayerTextDrawAlignment(playerid, speedometr[playerid][4], 1);
PlayerTextDrawColor(playerid, speedometr[playerid][4], -1);
PlayerTextDrawSetShadow(playerid, speedometr[playerid][4], 0);
PlayerTextDrawSetOutline(playerid, speedometr[playerid][4], 0);
PlayerTextDrawFont(playerid, speedometr[playerid][4], 4);

speedometr[playerid][5] = CreatePlayerTextDraw(playerid, 510.555450, 374.342285, "1000 hp");
PlayerTextDrawLetterSize(playerid, speedometr[playerid][5], 0.191777, 1.216709);
PlayerTextDrawAlignment(playerid, speedometr[playerid][5], 1);
PlayerTextDrawColor(playerid, speedometr[playerid][5], -1);
PlayerTextDrawSetShadow(playerid, speedometr[playerid][5], 0);
PlayerTextDrawSetOutline(playerid, speedometr[playerid][5], 0);
PlayerTextDrawBackgroundColor(playerid, speedometr[playerid][5], 51);
PlayerTextDrawFont(playerid, speedometr[playerid][5], 2);
PlayerTextDrawSetProportional(playerid, speedometr[playerid][5], 1);

speedometr[playerid][6] = CreatePlayerTextDraw(playerid, 595.888366, 374.840026, "120");
PlayerTextDrawLetterSize(playerid, speedometr[playerid][6], 0.495332, 3.013686);
PlayerTextDrawAlignment(playerid, speedometr[playerid][6], 1);
PlayerTextDrawColor(playerid, speedometr[playerid][6], -1);
PlayerTextDrawSetShadow(playerid, speedometr[playerid][6], 0);
PlayerTextDrawSetOutline(playerid, speedometr[playerid][6], 0);
PlayerTextDrawBackgroundColor(playerid, speedometr[playerid][6], 51);
PlayerTextDrawFont(playerid, speedometr[playerid][6], 2);
PlayerTextDrawSetProportional(playerid, speedometr[playerid][6], 1);

speedometr[playerid][7] = CreatePlayerTextDraw(playerid, 510.444305, 390.266632, "9999 km");
PlayerTextDrawLetterSize(playerid, speedometr[playerid][7], 0.191777, 1.216709);
PlayerTextDrawAlignment(playerid, speedometr[playerid][7], 1);
PlayerTextDrawColor(playerid, speedometr[playerid][7], -1);
PlayerTextDrawSetShadow(playerid, speedometr[playerid][7], 0);
PlayerTextDrawSetOutline(playerid, speedometr[playerid][7], 0);
PlayerTextDrawBackgroundColor(playerid, speedometr[playerid][7], 51);
PlayerTextDrawFont(playerid, speedometr[playerid][7], 2);
PlayerTextDrawSetProportional(playerid, speedometr[playerid][7], 1);

speedometr[playerid][8] = CreatePlayerTextDraw(playerid, 511.333312, 406.693237, "79 %");
PlayerTextDrawLetterSize(playerid, speedometr[playerid][8], 0.191777, 1.216709);
PlayerTextDrawAlignment(playerid, speedometr[playerid][8], 1);
PlayerTextDrawColor(playerid, speedometr[playerid][8], -1);
PlayerTextDrawSetShadow(playerid, speedometr[playerid][8], 0);
PlayerTextDrawSetOutline(playerid, speedometr[playerid][8], 0);
PlayerTextDrawBackgroundColor(playerid, speedometr[playerid][8], 51);
PlayerTextDrawFont(playerid, speedometr[playerid][8], 2);
PlayerTextDrawSetProportional(playerid, speedometr[playerid][8], 1);

speedometr[playerid][9] = CreatePlayerTextDraw(playerid, 598.222167, 395.751190, "KM/H");
PlayerTextDrawLetterSize(playerid, speedometr[playerid][9], 0.284665, 1.649775);
PlayerTextDrawAlignment(playerid, speedometr[playerid][9], 1);
PlayerTextDrawColor(playerid, speedometr[playerid][9], -668439399);
PlayerTextDrawSetShadow(playerid, speedometr[playerid][9], 0);
PlayerTextDrawSetOutline(playerid, speedometr[playerid][9], 0);
PlayerTextDrawBackgroundColor(playerid, speedometr[playerid][9], 51);
PlayerTextDrawFont(playerid, speedometr[playerid][9], 2);
PlayerTextDrawSetProportional(playerid, speedometr[playerid][9], 1);

speedometr[playerid][10] = CreatePlayerTextDraw(playerid, 576.888793, 371.857727, "LD_BEAT:chit");
PlayerTextDrawLetterSize(playerid, speedometr[playerid][10], 0.000000, 0.000000);
PlayerTextDrawTextSize(playerid, speedometr[playerid][10], 15.111118, 17.422237);
PlayerTextDrawAlignment(playerid, speedometr[playerid][10], 1);
PlayerTextDrawColor(playerid, speedometr[playerid][10], 780799999);
PlayerTextDrawSetShadow(playerid, speedometr[playerid][10], 0);
PlayerTextDrawSetOutline(playerid, speedometr[playerid][10], 0);
PlayerTextDrawFont(playerid, speedometr[playerid][10], 4);

speedometr[playerid][11] = CreatePlayerTextDraw(playerid, 576.777954, 403.711090, "LD_BEAT:chit");
PlayerTextDrawLetterSize(playerid, speedometr[playerid][11], 0.000000, 0.000000);
PlayerTextDrawTextSize(playerid, speedometr[playerid][11], 15.111118, 17.422237);
PlayerTextDrawAlignment(playerid, speedometr[playerid][11], 1);
PlayerTextDrawColor(playerid, speedometr[playerid][11], 780799999);
PlayerTextDrawSetShadow(playerid, speedometr[playerid][11], 0);
PlayerTextDrawSetOutline(playerid, speedometr[playerid][11], 0);
PlayerTextDrawFont(playerid, speedometr[playerid][11], 4);

speedometr[playerid][12] = CreatePlayerTextDraw(playerid, 555.111022, 406.204498, "LIGHT");
PlayerTextDrawLetterSize(playerid, speedometr[playerid][12], 0.191777, 1.216709);
PlayerTextDrawAlignment(playerid, speedometr[playerid][12], 1);
PlayerTextDrawColor(playerid, speedometr[playerid][12], -2139062017);
PlayerTextDrawSetShadow(playerid, speedometr[playerid][12], 0);
PlayerTextDrawSetOutline(playerid, speedometr[playerid][12], 0);
PlayerTextDrawBackgroundColor(playerid, speedometr[playerid][12], 51);
PlayerTextDrawFont(playerid, speedometr[playerid][12], 2);
PlayerTextDrawSetProportional(playerid, speedometr[playerid][12], 1);

speedometr[playerid][13] = CreatePlayerTextDraw(playerid, 549.888671, 374.351287, "ENGINE");
PlayerTextDrawLetterSize(playerid, speedometr[playerid][13], 0.191777, 1.216709);
PlayerTextDrawAlignment(playerid, speedometr[playerid][13], 1);
PlayerTextDrawColor(playerid, speedometr[playerid][13], -2139062017);
PlayerTextDrawSetShadow(playerid, speedometr[playerid][13], 0);
PlayerTextDrawSetOutline(playerid, speedometr[playerid][13], 0);
PlayerTextDrawBackgroundColor(playerid, speedometr[playerid][13], 51);
PlayerTextDrawFont(playerid, speedometr[playerid][13], 2);
PlayerTextDrawSetProportional(playerid, speedometr[playerid][13], 1);

speedometr[playerid][14] = CreatePlayerTextDraw(playerid, 555.333251, 390.284637, "door");
PlayerTextDrawLetterSize(playerid, speedometr[playerid][14], 0.191777, 1.216709);
PlayerTextDrawAlignment(playerid, speedometr[playerid][14], 1);
PlayerTextDrawColor(playerid, speedometr[playerid][14], -2139062017);
PlayerTextDrawSetShadow(playerid, speedometr[playerid][14], 0);
PlayerTextDrawSetOutline(playerid, speedometr[playerid][14], 0);
PlayerTextDrawBackgroundColor(playerid, speedometr[playerid][14], 51);
PlayerTextDrawFont(playerid, speedometr[playerid][14], 2);
PlayerTextDrawSetProportional(playerid, speedometr[playerid][14], 1);

speedometr[playerid][15] = CreatePlayerTextDraw(playerid, 576.889038, 387.786651, "LD_BEAT:chit");
PlayerTextDrawLetterSize(playerid, speedometr[playerid][15], 0.000000, 0.000000);
PlayerTextDrawTextSize(playerid, speedometr[playerid][15], 15.111118, 17.422237);
PlayerTextDrawAlignment(playerid, speedometr[playerid][15], 1);
PlayerTextDrawColor(playerid, speedometr[playerid][15], -1523963137);
PlayerTextDrawSetShadow(playerid, speedometr[playerid][15], 0);
PlayerTextDrawSetOutline(playerid, speedometr[playerid][15], 0);
PlayerTextDrawBackgroundColor(playerid, speedometr[playerid][15], -1523963137);
PlayerTextDrawFont(playerid, speedometr[playerid][15], 4);